// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Amnyam._3_Infrastructure.DataBase.EF;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Amnyam.Migrations
{
    [DbContext(typeof(MlkAdminDbContext))]
    [Migration("20260115150251_AddGuildMemberMetric")]
    partial class AddGuildMemberMetric
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Amnyam._1_Domain.Entities.GuildMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("Birthday")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birthday");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("discord_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsAuthorized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_authorized");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("RealName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("real_name");

                    b.Property<string>("TgName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tg_name");

                    b.Property<string>("VoiceRoomName")
                        .HasColumnType("text")
                        .HasColumnName("voice_room_name");

                    b.HasKey("Id");

                    b.ToTable("guild_member", (string)null);
                });

            modelBuilder.Entity("Amnyam._1_Domain.Entities.GuildMemberMetric", b =>
                {
                    b.Property<decimal>("MemberDiscordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("CommandsSentCount")
                        .HasColumnType("integer")
                        .HasColumnName("commands_sent_count");

                    b.Property<DateTimeOffset?>("FirstMessage")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_message_date");

                    b.Property<int>("GifsSentCount")
                        .HasColumnType("integer")
                        .HasColumnName("gifs_sent_count");

                    b.Property<DateTimeOffset?>("LastMessage")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_date");

                    b.Property<int>("MessageSentCount")
                        .HasColumnType("integer")
                        .HasColumnName("messages_sent_count");

                    b.Property<int>("PngPicturesSentCount")
                        .HasColumnType("integer")
                        .HasColumnName("pngpictures_sent_count");

                    b.Property<int>("ReactionAddedCount")
                        .HasColumnType("integer")
                        .HasColumnName("reaction_added_count");

                    b.Property<int>("StickersSentCount")
                        .HasColumnType("integer")
                        .HasColumnName("stickers_sent_count");

                    b.HasKey("MemberDiscordId");

                    b.ToTable("guilb_member_metrics", (string)null);
                });

            modelBuilder.Entity("Amnyam._1_Domain.Entities.GuildMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<decimal>("MessageDiscordId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("message_discord_id");

                    b.Property<decimal>("SenderDiscordId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("sender_discord_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<decimal>("TChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("from_t_channel_id");

                    b.Property<string>("TChannelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_t_channel_name");

                    b.HasKey("Id");

                    b.ToTable("guild_messages", (string)null);
                });

            modelBuilder.Entity("Amnyam._1_Domain.Entities.GuildTextChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("discord_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("text_channels", (string)null);
                });

            modelBuilder.Entity("Amnyam._1_Domain.Entities.GuildVoiceChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("discord_id");

                    b.Property<bool>("IsGen")
                        .HasColumnType("boolean")
                        .HasColumnName("is_gen");

                    b.Property<bool>("IsTemp")
                        .HasColumnType("boolean")
                        .HasColumnName("is_temp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("voice_channels", (string)null);
                });

            modelBuilder.Entity("Amnyam._1_Domain.Entities.GuildVoiceSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("EndingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ending_at");

                    b.Property<decimal>("GuildMemberDiscordId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset?>("StartingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starting_at");

                    b.Property<long>("TotalSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("time_in_seconds");

                    b.Property<decimal>("VChannelDiscordId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("vchannel_discord_id");

                    b.Property<string>("VChannelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("guild_voice_session", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
